version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    container_name: pg-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'pg-db'
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    user: root
    volumes:
      - ./src/infra/database/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql